# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppNational' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherAppNational
    pod 'SnapKit', '~> 5.6.0'
    pod 'IQKeyboardManagerSwift'
    pod 'FirebaseCore'
    pod 'FirebaseDatabase'
    pod 'FirebaseFirestore'
    pod 'FirebaseStorage'
    pod 'FirebaseMessaging'
    pod 'FirebaseAuth'
end
